import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const rubikFont = localFont({
	src: [
		{
			path: "/fonts/rubik-v28-latin-regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "/fonts/rubik-v28-latin-300.woff2",
			weight: "300",
			style: "light",
		},
		{
			path: "/fonts/rubik-v28-latin-500.woff2",
			weight: "500",
			style: "medium",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`w-full min-h-screen ${rubikFont.className} antialiased`}>
				<main className="w-full relative">{children}</main>
			</body>
		</html>
	);
}
