import "./styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

const rubikFont = localFont({
	src: [
		{
			path: "/fonts/Rubik-latin-regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "/fonts/Rubik-latin-300.woff2",
			weight: "300",
			style: "light",
		},
		{
			path: "/fonts/Rubik-latin-500.woff2",
			weight: "500",
			style: "medium",
		},
	],
});

export const metadata: Metadata = {
	title: "Lorenz Perszyk",
	description: "Generated by Lorenz Perszyk",
	icons: {
		icon: "/favicon.svg",
		shortcut: "/favicon.svg",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`w-full min-h-screen ${rubikFont.className} antialiased relative`}
			>
				<Navbar />
				<main className="w-full h-full relative bg-gray-100">
					{children}
					<Footer />
				</main>
			</body>
		</html>
	);
}
